// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'functional_test.dart' as functional_test;

void main() {
  functional_test.main();
}
